# site settings
title: Team R3
subtitle: Ryerson Rams Robotics
email: r3@ryerson.ca
description: R3 is Ryerson University's multidisciplinary robotics collective, with teams for every skill level.
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 43 Gerrard Street East
city: Toronto
state: Ontario
zip_code: 
country: Canada
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
